version: '3.8'

services:
  voice-typing:
    build: .
    container_name: ubuntu-voice-to-text
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - XDG_RUNTIME_DIR=/run/user/1000
    volumes:
      # X11 socket for GUI access
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # PulseAudio socket for audio access
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      # Alternative audio device access
      - /dev/snd:/dev/snd:rw
      # Vosk model directory (download model locally first)
      - ./vosk-model:/opt/vosk-model-small-en-us-0.15:ro
    devices:
      # Audio devices
      - /dev/snd:/dev/snd
    stdin_open: true
    tty: true
    restart: unless-stopped