version: '3.8'

services:
  voice-typing:
    build:
      context: .
      dockerfile: Dockerfile  # Default: Alpine (smaller image)
      # Alternative: Use Dockerfile.ubuntu for Ubuntu base
    container_name: ubuntu-voice-to-text
    network_mode: host
    # privileged: true # looks like it is working without this
    user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - XDG_RUNTIME_DIR=/run/user/1000
      - XAUTHORITY=/home/${USER}/.Xauthority
    volumes:
      # X11 socket for GUI access
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # PulseAudio socket for audio access
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      # Alternative audio device access
      - /dev/snd:/dev/snd:rw
      # Vosk model directory (download model locally first)
      # - ./vosk-model:/opt/vosk-model-small-en-us-0.15:ro # this is for CI
      # - .:/app:rw  # Mount source for development
      - /opt/vosk-model-small-en-us-0.15:/opt/vosk-model-small-en-us-0.15:ro # this is for development
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
    devices:
      # Audio devices
      - /dev/snd:/dev/snd
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Test runner service
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text-test
    command: ["test"]
    volumes:
      - .:/app/src:ro  # Mount source for development
    profiles:
      - test

  # Lint runner service
  lint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text-lint
    command: ["lint"]
    volumes:
      - .:/app/src:ro  # Mount source for development
    profiles:
      - test

  # Code formatter service
  format:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text-format
    command: ["format"]
    volumes:
      - .:/app/src:rw  # Mount source for writing formatted files
    profiles:
      - test

  # Alternative Ubuntu-based service
  voice-typing-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ubuntu-voice-to-text-ubuntu
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - XDG_RUNTIME_DIR=/run/user/1000
    volumes:
      # X11 socket for GUI access
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # PulseAudio socket for audio access
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      # Alternative audio device access
      - /dev/snd:/dev/snd:rw
      # Vosk model directory (download model locally first)
      - ./vosk-model:/opt/vosk-model-small-en-us-0.15:ro
    devices:
      # Audio devices
      - /dev/snd:/dev/snd
    stdin_open: true
    tty: true
    restart: unless-stopped
    profiles:
      - ubuntu  # Only start when explicitly requested
