version: '3.8'

services:
  voice-typing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text
    network_mode: host
    # privileged: true # looks like it is working without this
    user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - XDG_RUNTIME_DIR=/run/user/1000
      - XAUTHORITY=/home/${USER}/.Xauthority
      # Voice recognition configuration
      - RECOGNITION_SOURCE=${RECOGNITION_SOURCE:-vosk}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WHISPER_MODEL=${WHISPER_MODEL:-whisper-1}
    volumes:
      # X11 socket for GUI access
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # PulseAudio socket for audio access
      - /run/user/1000/pulse:/run/user/1000/pulse:rw
      # Alternative audio device access
      - /dev/snd:/dev/snd:rw
      - /home/${USER}/.Xauthority:/home/${USER}/.Xauthority:rw
      # Vosk model persistence directory (now as a named volume). Also need to chown in host OS (since this container runs as non-root user):
      # `sudo chown -R $(id -u):$(id -g) /var/lib/docker/volumes/ubuntu_voice_to_text_vosk-models/_data`
      - vosk-models:/models:rw
    devices:
      # Audio devices
      - /dev/snd:/dev/snd
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Test runner service
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text-test
    command: ["test"]
    volumes:
      - .:/app/src:ro  # Mount source for development
    profiles:
      - test

  # Lint runner service
  lint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text-lint
    command: ["lint"]
    volumes:
      - .:/app/src:ro  # Mount source for development
    profiles:
      - test

  # Code formatter service
  format:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-voice-to-text-format
    command: ["format"]
    volumes:
      - .:/app/src:rw  # Mount source for writing formatted files
    profiles:
      - test

volumes:
  vosk-models:
    driver: local
